export const SET_FIRST_STARTED = "SET_FIRST_STARTED";
export const ADD_STOP_FUNCTION = "ADD_STOP_FUNCTION";
export const STOP_TRACK = "STOP_TRACK";
export const UPDATE_STARTED_COUNT = "UPDATE_STARTED_COUNT";
